---
title: "NYC Restaurant Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)

library(plotly)

library(shiny)
```

```{r import_data}
nyc_inspections = read_csv("./DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>% 
  filter(grade %in% c("A", "B", "C")) %>% 
  mutate(inspection_num = row_number(),   
         boro = str_to_title(boro)) %>% 
  select(inspection_num, boro, grade, score, critical_flag, dba, cuisine_description, zipcode, violation_description) %>%
  filter(!is.na(score)) 


# take 20000 random sample
set.seed(123)
nyc_subdata = nyc_inspections[sample(nrow(nyc_inspections), 20000), ]
```

Column {.sidebar}
-----------------------------------------------------------------------
This `flexdashboard` with Shiny was made to explore the relationship between restaurant inspection scores and cuisine types in NYC.  The data comes from the New York City Department of Health and Mental Hygiene (DOHMH); there were 188,199 viable entries and we have randomly selected 10% of this population for analysis (20,000 total). Restaurant cumulative scores are converted into grades based on the following: a public health hazard, a critical violation, and/or a general violation. Lower scores earn a higher grade. The data used for this can be found  [here](http://jeffgoldsmith.com/DSI/dataset_restaurant_inspections.html). 


```{r}
boros = nyc_subdata %>% distinct(boro) %>% pull()

# selectInput widget
  selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")

hr()

# sliderInput widter
renderUI({
  max_score = nyc_subdata %>% filter(boro == input$boro_choice) %>% 
                           distinct(score) %>% max()
  
  min_score = nyc_subdata %>% filter(boro == input$boro_choice) %>% 
                           distinct(score) %>% min()
  
  sliderInput("score_range", label = h3("Choose score range"), min = min_score, 
        max = max_score, value = c(-1, 86))
})  

# value: default value range when it shows up

hr()

grade_choice = nyc_subdata %>% distinct(grade) %>% pull()

# radioButtons widget
radioButtons("grade_choice", label = h3("Choose Grade type"),
    choices = grade_choice, 
    selected = "A")

```

Row 
-----------------------------------------------------------------------

###Scatterplot: Restaurant Inspection Scores by Zipcode

```{r}
renderPlotly({
  nyc_subdata %>%
  filter(boro == input$boro_choice, 
           score %in% input$score_range[1]:input$score_range[2],
           grade == input$grade_choice) %>%
  mutate(text_label = str_c("Score: ", score, '\ngrade: ', grade)) %>% 
  filter(boro == input$boro_choice) %>%
  plot_ly(x = ~zipcode, y = ~score, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~score,
          text = ~text_label) %>%
  layout(legend = list(x = 100, y = 0.5)) %>%
  layout(
    title = "Restaurant Score by Zipcode") %>%
    layout(yaxis = list(title = 'Restaurant Score')) %>%
    layout(xaxis = list(title = 'Zipcode'))
})
```

Row {.tabset .tabset-fade } 
-----------------------------------------------------------------------

### Most Common Cuisines in NYC (Bar Chart)

```{r}
renderPlotly({
  nyc_subdata %>% 
  filter(boro == input$boro_choice, 
           score %in% input$score_range[1]:input$score_range[2],
           grade == input$grade_choice) %>%
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  top_n(10) %>%
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "Set2") %>%
  layout(legend = list(x = 100, y = 0.5)) %>%
  layout(
    title = "Most Common Cuisines in NYC") %>%
    layout(yaxis = list(title = 'Number of Restaurants')) %>%
    layout(xaxis = list(title = 'Cuisine Type'))
})
```

### Boxplot of the Restaurant's Inspection Score for the top five most popular cuisines in NYC

```{r}
renderPlotly({
  common_cuisine =
  nyc_subdata %>% 
    filter(boro == input$boro_choice, 
           score %in% input$score_range[1]:input$score_range[2],
           grade == input$grade_choice) %>%
  count(cuisine_description, sort = TRUE) %>% 
  top_n(10) %>% 
  select(cuisine_description)

nyc_subdata %>% 
filter(cuisine_description %in% c("American", "Chinese","Italian","Pizza","Mexican")) %>% 
filter(boro == input$boro_choice, 
           score %in% input$score_range[1]:input$score_range[2],
           grade == input$grade_choice) %>%
inner_join(., common_cuisine,
             by = "cuisine_description") %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2") %>%
   layout(legend = list(x = 100, y = 0.5)) %>%
    layout(
    title = "Distribution of restaurant score in the most popular cuisines in NYC") %>%
    layout(yaxis = list(title = 'Restaurant Score')) %>%
    layout(xaxis = list(title = 'Cuisine Type'))
})
```